#!/bin/bash
# Generated by cc-statusline v1.4.0 (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2026-01-01T02:06:25.732Z
# Theme: detailed | Colors: true | Features: directory, git, model, context
STATUSLINE_VERSION="1.4.0"

input=$(cat)

# ---- check jq availability ----
HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

# Get the directory where this statusline script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="${SCRIPT_DIR}/statusline.log"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# ---- logging ----
{
  echo "[$TIMESTAMP] Status line triggered (cc-statusline v${STATUSLINE_VERSION})"
  echo "[$TIMESTAMP] Input:"
  if [ "$HAS_JQ" -eq 1 ]; then
    echo "$input" | jq . 2>/dev/null || echo "$input"
    echo "[$TIMESTAMP] Using jq for JSON parsing"
  else
    echo "$input"
    echo "[$TIMESTAMP] WARNING: jq not found, using bash fallback for JSON parsing"
  fi
  echo "---"
} >> "$LOG_FILE" 2>/dev/null

# ---- color helpers (force colors for Claude Code) ----
use_color=1
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- line 2 colors (basic 16-color to reduce ANSI byte overhead) ----
# 256-color codes (\033[38;5;NNNm = 12 bytes) cause Claude Code width
# miscalculation. Basic codes (\033[NNm = 5 bytes) halve the overhead.
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[94m'; fi; }    # bright blue
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[95m'; fi; }  # bright magenta
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[93m'; fi; } # bright yellow
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

fmt_time_hm() {
  epoch="$1"
  if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- JSON extraction utilities ----
# Pure bash JSON value extractor (fallback when jq not available)
extract_json_string() {
  local json="$1"
  local key="$2"
  local default="${3:-}"
  
  # For nested keys like workspace.current_dir, get the last part
  local field="${key##*.}"
  field="${field%% *}"  # Remove any jq operators
  
  # Try to extract string value (quoted)
  local value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -1 | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/')
  
  # Convert escaped backslashes to forward slashes for Windows paths
  if [ -n "$value" ]; then
    value=$(echo "$value" | sed 's/\\\\/\//g')
  fi
  
  # If no string value found, try to extract number value (unquoted)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*[0-9.]\+" | head -1 | sed 's/.*:[[:space:]]*\([0-9.]\+\).*/\1/')
  fi
  
  # Return value or default
  if [ -n "$value" ] && [ "$value" != "null" ]; then
    echo "$value"
  else
    echo "$default"
  fi
}

# ---- basics ----
if [ "$HAS_JQ" -eq 1 ]; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
  agent_name=$(echo "$input" | jq -r '.agent.name // ""' 2>/dev/null)
else
  # Bash fallback for JSON extraction
  # Extract current_dir from workspace object - look for the pattern workspace":{"current_dir":"..."}
  current_dir=$(echo "$input" | grep -o '"workspace"[[:space:]]*:[[:space:]]*{[^}]*"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"current_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  
  # Fall back to cwd if workspace extraction failed
  if [ -z "$current_dir" ] || [ "$current_dir" = "null" ]; then
    current_dir=$(echo "$input" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  fi
  
  # Fallback to unknown if all extraction failed
  [ -z "$current_dir" ] && current_dir="unknown"
  current_dir=$(echo "$current_dir" | sed "s|^$HOME|~|g")
  
  # Extract model name from nested model object
  model_name=$(echo "$input" | grep -o '"model"[[:space:]]*:[[:space:]]*{[^}]*"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"display_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  # Model version is in the model ID, not a separate field  
  model_version=""  # Not available in Claude Code JSON
  # Extract agent name from nested agent object
  agent_name=$(echo "$input" | grep -o '"agent"[[:space:]]*:[[:space:]]*{[^}]*"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$agent_name" ] && agent_name=""
fi

# ---- agent color (basic 16-color) ----
agent_color() { if [ "$use_color" -eq 1 ]; then printf '\033[96m'; fi; }  # bright cyan

# ---- git colors (basic 16-color) ----
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[92m'; fi; }  # bright green
git_clean_color() { if [ "$use_color" -eq 1 ]; then printf '\033[92m'; fi; }  # bright green
git_dirty_color() { if [ "$use_color" -eq 1 ]; then printf '\033[93m'; fi; }  # bright yellow
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- git ----
# GIT_OPTIONAL_LOCKS=0 prevents git from acquiring index.lock for read-only
# operations. Without this, frequent statusline refreshes can leave stale
# index.lock files that block interactive git commands in the same repo.
git_branch=""
git_dirty=""
if GIT_OPTIONAL_LOCKS=0 git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(GIT_OPTIONAL_LOCKS=0 git branch --show-current 2>/dev/null || GIT_OPTIONAL_LOCKS=0 git rev-parse --short HEAD 2>/dev/null)
  if [ -n "$(GIT_OPTIONAL_LOCKS=0 git status --porcelain 2>/dev/null)" ]; then
    git_dirty=1
  else
    git_dirty=0
  fi
fi

# ---- context window calculation (native) ----
context_pct=""
context_remaining_pct=""
context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;37m'; fi; }  # default white

if [ "$HAS_JQ" -eq 1 ]; then
  # Get context window size and current usage from native Claude Code input
  CONTEXT_SIZE=$(echo "$input" | jq -r '.context_window.context_window_size // 200000' 2>/dev/null)
  USAGE=$(echo "$input" | jq '.context_window.current_usage' 2>/dev/null)

  if [ "$USAGE" != "null" ] && [ -n "$USAGE" ]; then
    # Calculate current context from current_usage fields
    # Formula: input_tokens + cache_creation_input_tokens + cache_read_input_tokens
    CURRENT_TOKENS=$(echo "$USAGE" | jq '(.input_tokens // 0) + (.cache_creation_input_tokens // 0) + (.cache_read_input_tokens // 0)' 2>/dev/null)

    if [ -n "$CURRENT_TOKENS" ] && [ "$CURRENT_TOKENS" -gt 0 ] 2>/dev/null; then
      context_used_pct=$(( CURRENT_TOKENS * 100 / CONTEXT_SIZE ))
      context_remaining_pct=$(( 100 - context_used_pct ))
      # Clamp to valid range
      (( context_remaining_pct < 0 )) && context_remaining_pct=0
      (( context_remaining_pct > 100 )) && context_remaining_pct=100

      # Set color based on remaining percentage
      if [ "$context_remaining_pct" -le 20 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
      elif [ "$context_remaining_pct" -le 40 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
      else
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
      fi

      context_pct="${context_remaining_pct}%"
    fi
  fi
fi

# ---- log extracted data ----
{
  echo "[$TIMESTAMP] Extracted: dir=${current_dir:-}, model=${model_name:-}, version=${model_version:-}, git=${git_branch:-}, context=${context_pct:-}, agent=${agent_name:-}"
  if [ "$HAS_JQ" -eq 0 ]; then
    echo "[$TIMESTAMP] Note: Context, tokens, and session info require jq for full functionality"
  fi
} >> "$LOG_FILE" 2>/dev/null

# ---- render statusline ----
# 3 output lines, shortest first so narrow terminals degrade gracefully.
#
# Line 1: Context + model (always visible)
# Line 2: Dir (basename) / git
# Line 3: Lifecycle / agent (can truncate without affecting lines 1-2)

# ---- Line 1: Context + model ----
if [ -n "$context_pct" ]; then
  context_bar=$(progress_bar "$context_remaining_pct" 10)
  printf '🧠 %s%s [%s]%s' "$(context_color)" "$context_pct" "$context_bar" "$(rst)"
else
  printf '🧠 %s--%s' "$(context_color)" "$(rst)"
fi
printf '  🤖 %s%s%s' "$(model_color)" "$model_name" "$(rst)"
if [ -n "$model_version" ] && [ "$model_version" != "null" ]; then
  printf '  🏷️ %s%s%s' "$(version_color)" "$model_version" "$(rst)"
fi

# ---- Line 2: Dir (basename) / git ----
dir_basename="${current_dir##*/}"
printf '\n📁 %s%s%s' "$(dir_color)" "$dir_basename" "$(rst)"
if [ -n "$git_branch" ]; then
  if [ "$git_dirty" = "1" ]; then
    printf '  🌿 %s%s%s %s●%s' "$(git_color)" "$git_branch" "$(rst)" "$(git_dirty_color)" "$(rst)"
  else
    printf '  🌿 %s%s%s %s✓%s' "$(git_color)" "$git_branch" "$(rst)" "$(git_clean_color)" "$(rst)"
  fi
fi

# ---- Line 4: Lifecycle state (conditional) ----
# Scan for active lifecycle feature and display phase/progress.
# Optimized for speed: test -f artifact detection, single grep -c for progress.
lifecycle_line=""
_refined_indicator=""

# Resolve working directory (undo ~ substitution)
_lc_dir="${current_dir/#\~/$HOME}"
_lc_base="$_lc_dir/lifecycle"

if [ -d "$_lc_base" ]; then
  # --- Pipeline display (takes priority over single-feature display) ---
  _lc_overnight_file="$_lc_base/overnight-state.json"
  _lc_pipeline_handled=0

  if [ -f "$_lc_overnight_file" ]; then
    _pl_phase=""
    _pl_total=0
    _pl_merged=0
    _pl_active_names=""
    _pl_merged_names=""

    if [ "$HAS_JQ" -eq 1 ]; then
      # Single jq call extracts phase, total count, merged count, active feature names, and merged feature names
      _pl_data=$(jq -r '
        [.phase,
         ([.features[]] | length),
         ([.features[] | select(.status == "complete" or .status == "merged")] | length),
         ([.features | to_entries[] | select(.value.status == "executing" or .value.status == "reviewing" or .value.status == "merging") | .key] | join(", ")),
         ([.features | to_entries[] | select(.value.status == "merged") | .key] | join("|"))
        ] | @tsv' "$_lc_overnight_file" 2>/dev/null)
      if [ -n "$_pl_data" ]; then
        _pl_phase=$(printf '%s' "$_pl_data" | cut -f1)
        _pl_total=$(printf '%s' "$_pl_data" | cut -f2)
        _pl_merged=$(printf '%s' "$_pl_data" | cut -f3)
        _pl_active_names=$(printf '%s' "$_pl_data" | cut -f4)
        _pl_merged_names=$(printf '%s' "$_pl_data" | cut -f5)
      fi
    else
      # Bash fallback: extract phase and count features by status
      _pl_phase=$(grep -o '"phase"[[:space:]]*:[[:space:]]*"[^"]*"' "$_lc_overnight_file" 2>/dev/null | head -1 | sed 's/.*"\([^"]*\)"[[:space:]]*$/\1/')
      _pl_total=$(grep -c '"status"[[:space:]]*:' "$_lc_overnight_file" 2>/dev/null) || _pl_total=0
      _pl_merged=$(grep -cE '"status"[[:space:]]*:[[:space:]]*"(complete|merged)"' "$_lc_overnight_file" 2>/dev/null) || _pl_merged=0
      # Extract active feature names (executing/reviewing/merging) and merged feature names via grep on the raw JSON
      # This is a best-effort heuristic for the bash fallback
      _pl_active_names=""
      _pl_merged_names=""
      _pl_in_features=0
      while IFS= read -r _pl_line; do
        if echo "$_pl_line" | grep -q '"features"'; then _pl_in_features=1; continue; fi
        if [ "$_pl_in_features" -eq 1 ]; then
          _pl_feat_name=$(echo "$_pl_line" | grep -o '"[^"]*"[[:space:]]*:[[:space:]]*{' | sed 's/"\([^"]*\)".*/\1/')
          if [ -n "$_pl_feat_name" ]; then _pl_cur_feat="$_pl_feat_name"; fi
          if echo "$_pl_line" | grep -qE '"status"[[:space:]]*:[[:space:]]*"(executing|reviewing|merging)"'; then
            if [ -n "$_pl_active_names" ]; then
              _pl_active_names="$_pl_active_names, $_pl_cur_feat"
            else
              _pl_active_names="$_pl_cur_feat"
            fi
          fi
          if echo "$_pl_line" | grep -qE '"status"[[:space:]]*:[[:space:]]*"merged"'; then
            if [ -n "$_pl_merged_names" ]; then
              _pl_merged_names="$_pl_merged_names|$_pl_cur_feat"
            else
              _pl_merged_names="$_pl_cur_feat"
            fi
          fi
        fi
      done < "$_lc_overnight_file"
    fi

    _lc_icon_color='\033[95m'   # bright magenta (basic 16-color)
    _lc_name_color='\033[97m'   # bright white
    _lc_rst='\033[0m'

    # Phase == complete: show Morning Review indicator (unless dismissed)
    if [ -n "$_pl_phase" ] && [ "$_pl_phase" = "complete" ]; then
      _mr_dismissed=0
      if [ "$HAS_JQ" -eq 1 ] && [ -n "$_pl_merged_names" ]; then
        # Check dismissal: all merged features must have a feature_complete event
        _mr_dismissed=1
        IFS='|' read -ra _mr_names <<< "$_pl_merged_names"
        for _mr_name in "${_mr_names[@]}"; do
          _mr_events_log="$_lc_base/$_mr_name/events.log"
          if [ ! -f "$_mr_events_log" ] || ! grep -q '"feature_complete"' "$_mr_events_log" 2>/dev/null; then
            _mr_dismissed=0
            break
          fi
        done
      fi
      # If jq unavailable: skip dismissal check, always show Morning Review
      # If no merged names: show Morning Review (phase=complete with 0 merged is unusual but valid)

      if [ "$_mr_dismissed" -eq 0 ]; then
        # Not dismissed: show Morning Review indicator
        _lc_pipeline_handled=1
        lifecycle_line=$(printf "${_lc_icon_color}☀️ Morning Review: ${_lc_name_color}%s${_lc_rst}" "$_pl_merged")
      else
        # Dismissed: fall through to per-feature scan
        _lc_pipeline_handled=0
      fi

    # Phase != complete: suppress single-feature fallback for active pipelines
    elif [ -n "$_pl_phase" ] && [ "$_pl_phase" != "complete" ]; then
      _lc_pipeline_handled=1

      if [ -n "$_pl_active_names" ]; then
        lifecycle_line=$(printf "${_lc_icon_color}🔄 Pipeline: ${_lc_name_color}%s/%s done${_lc_rst} · ${_lc_icon_color}%s${_lc_rst} [${_lc_name_color}%s${_lc_rst}]" "$_pl_merged" "$_pl_total" "$_pl_phase" "$_pl_active_names")
      else
        lifecycle_line=$(printf "${_lc_icon_color}🔄 Pipeline: ${_lc_name_color}%s/%s done${_lc_rst} · ${_lc_icon_color}%s${_lc_rst}" "$_pl_merged" "$_pl_total" "$_pl_phase")
      fi
    fi
  fi

  # --- Phase icon helper ---
  _lc_phase_icon() {
    case "$1" in
      research)         printf '📚' ;;
      specify)          printf '✏️' ;;
      plan)             printf '📋' ;;
      implement:*|implement) printf '🔨' ;;
      implement-rework) printf '🔨' ;;
      review)           printf '🔎' ;;
      escalated)        printf '⚠️' ;;
      *)                printf '🔄' ;;
    esac
  }

  # --- Single-feature display (fallback when no active pipeline) ---
  if [ "$_lc_pipeline_handled" -eq 0 ]; then
  # Collect all incomplete features: "name|phase" entries
  _lc_incomplete_features=()

  for _lc_fdir in "$_lc_base"/*/; do
    [ -d "$_lc_fdir" ] || continue
    [ -f "${_lc_fdir}.no-lifecycle" ] && continue
    _lc_fname="${_lc_fdir%/}"
    _lc_fname="${_lc_fname##*/}"

    # --- Phase detection (bash-only mirror of cortex_command.common.detect_lifecycle_phase) ---
    #
    # STRUCTURAL EXCEPTION: This is a deliberate bash-only mirror of
    # cortex_command.common.detect_lifecycle_phase(). The statusline operates under
    # a < 500ms render latency budget (see cortex/requirements/observability.md:23, 91),
    # which prohibits subprocessing to a Python interpreter on every render. All
    # other lifecycle phase detection in the codebase delegates to the canonical
    # Python implementation; the statusline is the documented exception.
    #
    # Equivalence between this bash ladder and the canonical Python function is
    # enforced by the parity test at tests/test_lifecycle_phase_parity.py. If you
    # change the phase detection logic here, update the canonical implementation
    # in cortex_command.common AND ensure the parity test still passes. Do not
    # "fix" this apparent duplication by collapsing it into a Python call.
    _lc_phase=""
    # Pre-scan events.log once for approval events and migration sentinels.
    _lc_spec_approved=0
    _lc_plan_approved=0
    _lc_spec_transitioned_out=0
    _lc_plan_transitioned_out=0
    if [ -f "$_lc_fdir/events.log" ]; then
      grep -q '"event"[[:space:]]*:[[:space:]]*"spec_approved"' "$_lc_fdir/events.log" 2>/dev/null && _lc_spec_approved=1
      grep -q '"event"[[:space:]]*:[[:space:]]*"plan_approved"' "$_lc_fdir/events.log" 2>/dev/null && _lc_plan_approved=1
      grep -qE '"event"[[:space:]]*:[[:space:]]*"phase_transition"[^}]*"from"[[:space:]]*:[[:space:]]*"specify"' "$_lc_fdir/events.log" 2>/dev/null && _lc_spec_transitioned_out=1
      grep -qE '"event"[[:space:]]*:[[:space:]]*"phase_transition"[^}]*"from"[[:space:]]*:[[:space:]]*"plan"' "$_lc_fdir/events.log" 2>/dev/null && _lc_plan_transitioned_out=1
    fi

    if [ -f "$_lc_fdir/events.log" ] && grep -q '"feature_complete"' "$_lc_fdir/events.log" 2>/dev/null; then
      _lc_phase="complete"
    elif [ -f "$_lc_fdir/review.md" ]; then
      _lc_verdict=$(grep -o '"verdict"[[:space:]]*:[[:space:]]*"[A-Z_]*"' "$_lc_fdir/review.md" 2>/dev/null | tail -1 | sed 's/.*"\([A-Z_]*\)".*/\1/')
      case "$_lc_verdict" in
        APPROVED)          _lc_phase="complete" ;;
        CHANGES_REQUESTED) _lc_phase="implement-rework" ;;
        REJECTED)          _lc_phase="escalated" ;;
      esac
    fi

    if [ -z "$_lc_phase" ] && [ -f "$_lc_fdir/plan.md" ]; then
      if [ "$_lc_plan_approved" -eq 0 ] && [ "$_lc_plan_transitioned_out" -eq 0 ]; then
        _lc_phase="plan"
      else
        _lc_total=$(grep -cE '\*\*Status\*\*:.*\[[ x]\]' "$_lc_fdir/plan.md" 2>/dev/null) || _lc_total=0
        _lc_checked=$(grep -cE '\*\*Status\*\*:.*\[x\]' "$_lc_fdir/plan.md" 2>/dev/null) || _lc_checked=0
        if [ "$_lc_total" -gt 0 ] && [ "$_lc_checked" -eq "$_lc_total" ]; then
          _lc_phase="review"
        else
          _lc_phase="implement:$_lc_checked/$_lc_total"
        fi
      fi
    fi

    if [ -z "$_lc_phase" ] && [ -f "$_lc_fdir/spec.md" ]; then
      if [ "$_lc_spec_approved" -eq 0 ] && [ "$_lc_spec_transitioned_out" -eq 0 ]; then
        _lc_phase="specify"
      else
        _lc_phase="plan"
      fi
    fi
    [ -z "$_lc_phase" ] && [ -f "$_lc_fdir/research.md" ] && _lc_phase="specify"
    [ -z "$_lc_phase" ] && _lc_phase="research"

    # Skip completed features
    [ "$_lc_phase" = "complete" ] && continue

    # Collect all incomplete features
    _lc_incomplete_features+=("${_lc_fname}|${_lc_phase}")
  done

  # Build the lifecycle status line (basic 16-color to reduce ANSI byte overhead)
  _lc_icon_color='\033[95m'   # bright magenta
  _lc_name_color='\033[97m'   # bright white
  _lc_rst='\033[0m'

  # Helper: append a segment to lifecycle_line (newline-separated)
  _lc_append() {
    if [ -z "$lifecycle_line" ]; then
      lifecycle_line="$1"
    else
      lifecycle_line="${lifecycle_line}$(printf '\n%s' "$1")"
    fi
  }

  # Step 1 — split Review (overnight vs manual) from other
  _lc_overnight_review_count=0
  _lc_manual_review_features=()
  _lc_other_features=()
  for _lc_entry in "${_lc_incomplete_features[@]}"; do
    _lc_entry_phase="${_lc_entry##*|}"
    _lc_entry_name="${_lc_entry%%|*}"
    if [ "$_lc_entry_phase" = "review" ]; then
      if [ -f "$_lc_base/$_lc_entry_name/agent-activity.jsonl" ]; then
        _lc_overnight_review_count=$(( _lc_overnight_review_count + 1 ))
      else
        _lc_manual_review_features+=("$_lc_entry")
      fi
    else
      _lc_other_features+=("$_lc_entry")
    fi
  done

  # Step 2 — Morning Review indicator (overnight-processed features only)
  if [ "$_lc_overnight_review_count" -gt 0 ]; then
    _lc_append "$(printf "${_lc_icon_color}☀️ Morning Review: ${_lc_name_color}%s${_lc_rst}" "$_lc_overnight_review_count")"
  fi

  # Step 2b — Manual review features (not from overnight)
  _lc_manual_review_count="${#_lc_manual_review_features[@]}"
  if [ "$_lc_manual_review_count" -eq 1 ]; then
    _lc_single_entry="${_lc_manual_review_features[0]}"
    _lc_single_name="${_lc_single_entry%%|*}"
    _lc_icon="$(_lc_phase_icon "review")"
    _lc_append "$(printf "${_lc_icon_color}%s ${_lc_name_color}%s${_lc_rst} · ${_lc_icon_color}%s${_lc_rst}" "$_lc_icon" "$_lc_single_name" "Review")"
  elif [ "$_lc_manual_review_count" -ge 2 ]; then
    _lc_icon="$(_lc_phase_icon "review")"
    _lc_append "$(printf "${_lc_icon_color}%s ${_lc_name_color}%s${_lc_rst}" "$_lc_icon" "${_lc_manual_review_count} In Review")"
  fi

  # Step 3 — Group non-review by phase (bash 3.2 compatible, parallel indexed arrays)
  _lc_phases_seen=()
  _lc_phase_counts=()
  _lc_phase_names=()   # pipe-separated list of feature names per phase

  for _lc_entry in "${_lc_other_features[@]}"; do
    _lc_entry_name="${_lc_entry%%|*}"
    _lc_entry_phase="${_lc_entry##*|}"

    # Normalize phase key for grouping: strip implement:N/M counts to "implement"
    case "$_lc_entry_phase" in
      implement:*) _lc_phase_key="implement" ;;
      *)           _lc_phase_key="$_lc_entry_phase" ;;
    esac

    # Check if this phase key is already tracked
    _lc_phase_idx=-1
    _lc_i=0
    for _lc_seen in "${_lc_phases_seen[@]}"; do
      if [ "$_lc_seen" = "$_lc_phase_key" ]; then
        _lc_phase_idx=$_lc_i
        break
      fi
      _lc_i=$(( _lc_i + 1 ))
    done

    if [ "$_lc_phase_idx" -eq -1 ]; then
      # New phase — append
      _lc_phases_seen+=("$_lc_phase_key")
      _lc_phase_counts+=("1")
      _lc_phase_names+=("$_lc_entry_name|$_lc_entry_phase")
    else
      # Existing phase — increment count, append name+phase entry
      _lc_phase_counts[$_lc_phase_idx]=$(( _lc_phase_counts[$_lc_phase_idx] + 1 ))
      _lc_phase_names[$_lc_phase_idx]="${_lc_phase_names[$_lc_phase_idx]}|||${_lc_entry_name}|${_lc_entry_phase}"
    fi
  done

  # Step 4 — Render N≥2 groups first, then N=1 singles (in discovery order)
  # Two passes: first N≥2, then N=1
  for _lc_pass in "multi" "single"; do
    _lc_i=0
    for _lc_phase_key in "${_lc_phases_seen[@]}"; do
      _lc_count="${_lc_phase_counts[$_lc_i]}"
      _lc_entries_str="${_lc_phase_names[$_lc_i]}"
      _lc_i=$(( _lc_i + 1 ))

      if [ "$_lc_pass" = "multi" ] && [ "$_lc_count" -ge 2 ]; then
        # N≥2: emit "N Phase-display-text"
        _lc_icon="$(_lc_phase_icon "$_lc_phase_key")"
        case "$_lc_phase_key" in
          research)         _lc_display="Research" ;;
          specify)          _lc_display="Specify" ;;
          plan)             _lc_display="Plan" ;;
          implement)        _lc_display="Implement" ;;
          implement-rework) _lc_display="Implement (rework)" ;;
          escalated)        _lc_display="Escalated" ;;
          *)                _lc_display="$_lc_phase_key" ;;
        esac
        _lc_append "$(printf "${_lc_icon_color}%s ${_lc_name_color}%s${_lc_rst}" "$_lc_icon" "${_lc_count} ${_lc_display}")"

      elif [ "$_lc_pass" = "single" ] && [ "$_lc_count" -eq 1 ]; then
        # N=1: emit full format (icon + name + phase + optional progress bar)
        # The single entry is stored as "name|phase" in _lc_entries_str
        _lc_single_name="${_lc_entries_str%%|*}"
        _lc_single_phase="${_lc_entries_str##*|}"

        _lc_icon="$(_lc_phase_icon "$_lc_single_phase")"

        case "$_lc_single_phase" in
          research)         _lc_display="Research" ;;
          specify)          _lc_display="Specify" ;;
          plan)             _lc_display="Plan" ;;
          implement-rework) _lc_display="Implement (rework)" ;;
          escalated)        _lc_display="Escalated" ;;
          implement:*)
            _lc_frac="${_lc_single_phase#implement:}"
            _lc_checked="${_lc_frac%%/*}"
            _lc_total="${_lc_frac##*/}"
            _lc_p_pct=0
            if [ "$_lc_total" -gt 0 ] 2>/dev/null; then
              _lc_p_pct=$(( _lc_checked * 100 / _lc_total ))
            fi
            _lc_progress_bar="$(progress_bar "$_lc_p_pct" 10)"
            _lc_display="Implement ${_lc_checked}/${_lc_total}"
            _lc_append "$(printf "${_lc_icon_color}%s ${_lc_name_color}%s${_lc_rst} · ${_lc_icon_color}%s${_lc_rst} [%s]" "$_lc_icon" "$_lc_single_name" "$_lc_display" "$_lc_progress_bar")"
            continue
            ;;
          *) _lc_display="$_lc_single_phase" ;;
        esac
        _lc_append "$(printf "${_lc_icon_color}%s ${_lc_name_color}%s${_lc_rst} · ${_lc_icon_color}%s${_lc_rst}" "$_lc_icon" "$_lc_single_name" "$_lc_display")"
      fi
    done
  done

  fi  # end _lc_pipeline_handled check

  # ---- Refined backlog count indicator ----
  # Count backlog items with status: refined and show indicator if >= 2.
  # Skip items already active in a lifecycle (avoids duplication).
  _refined_count=0
  for _f in "$_lc_dir/backlog"/[0-9]*-*.md; do
    head -20 "$_f" 2>/dev/null | grep -q '^status: refined' || continue
    _bl_slug="${_f##*/}"; _bl_slug="${_bl_slug%.md}"
    _bl_name="${_bl_slug#*-}"  # strip leading NNN- to get the feature name part
    # Skip if the feature name matches any active lifecycle directory
    _bl_active=0
    for _lc_entry in "${_lc_incomplete_features[@]}"; do
      _lc_entry_name="${_lc_entry%%|*}"
      case "$_lc_entry_name" in *"$_bl_name"*) _bl_active=1; break ;; esac
    done
    [ "$_bl_active" -eq 1 ] && continue
    _refined_count=$(( _refined_count + 1 ))
  done
  if [ "$_refined_count" -gt 1 ]; then
    _refined_indicator=$(printf '%s%s Refined%s' "$(version_color)" "$_refined_count" "$(rst)")
  fi
fi

# ---- Build agent indicator ----
agent_indicator=""
if [ -n "$agent_name" ]; then
  agent_indicator=$(printf '%s⚡ %s%s' "$(agent_color)" "$agent_name" "$(rst)")
fi

# ---- Line 3: Lifecycle and/or agent (own row, can truncate freely) ----
_line3=""
[ -n "$lifecycle_line" ] && _line3="$lifecycle_line"
[ -n "$agent_indicator" ] && {
  if [ -n "$_line3" ]; then _line3="$_line3  $agent_indicator"; else _line3="$agent_indicator"; fi
}
[ -n "$_refined_indicator" ] && {
  if [ -n "$_line3" ]; then _line3="$_line3  $_refined_indicator"; else _line3="$_refined_indicator"; fi
}
if [ -n "$_line3" ]; then
  printf '\n%s' "$_line3"
fi
printf '\n'

# ---- Debug: log byte counts for truncation diagnosis ----
{
  _dbg_ctx="🧠 ${context_pct:---}"
  [ -n "$context_pct" ] && _dbg_ctx="🧠 ${context_pct} [$(progress_bar "$context_remaining_pct" 10)]"
  _dbg_l2="📁 ${current_dir}"
  [ -n "$git_branch" ] && _dbg_l2="${_dbg_l2}  🌿 ${git_branch}"
  _dbg_l2="${_dbg_l2}  🤖 ${model_name}"
  [ -n "$lifecycle_line" ] && _dbg_l2="${_dbg_l2}  │  (lifecycle)"
  echo "[$TIMESTAMP] Output: 2 lines. L1 visible='${_dbg_ctx}' ($(printf '%s' "$_dbg_ctx" | wc -c | tr -d ' ')b) L2 visible='${_dbg_l2}' ($(printf '%s' "$_dbg_l2" | wc -c | tr -d ' ')b)"
} >> "$LOG_FILE" 2>/dev/null
