"""Unit tests for ``_commit_morning_report_in_repo`` (lifecycle ticket
install-pre-commit-hook-rejecting-main-commits-during-overnight-sessions,
Task 12).

Covers Req 9 of the spec: the runner-side morning-report commit step ported
from the legacy ``runner.sh`` to ``runner.py``. The function must:

(a) commit successfully when ``lifecycle/morning-report.md`` has staged
    content and emit a ``MORNING_REPORT_COMMIT_RESULT`` event whose
    ``outcome`` field is ``"committed"``.
(b) no-op cleanly when nothing is staged. Per inspection of
    ``runner.py:_commit_morning_report_in_repo``, the no-op path is the
    early ``return`` after ``git diff --cached --quiet`` returns 0, which
    emits NO event. This test therefore asserts that no
    ``MORNING_REPORT_COMMIT_RESULT`` or ``MORNING_REPORT_COMMIT_FAILED``
    line appears in the events log on the no-op path. (Implementer choice
    documented per spec.)

Architectural invariant under test: the function must commit without
``CORTEX_RUNNER_CHILD=1`` set in the test environment, since
``_commit_morning_report_in_repo`` runs in the runner process — above
Phase 0 — and the pre-commit hook only fires for runner-spawned children.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest


def _git(cwd: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    """Run a git command with baked-in identity flags so commits succeed
    regardless of the test runner's user.* config or signing setup."""
    return subprocess.run(
        ["git",
         "-c", "user.email=t@t",
         "-c", "user.name=T",
         "-c", "commit.gpgsign=false",
         *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=check,
    )


def _init_repo(path: Path) -> None:
    """Initialize an ephemeral repo with a single empty initial commit and
    local user identity baked in (so subsequent un-flagged ``git commit``
    invocations from the system-under-test inherit usable config)."""
    path.mkdir(parents=True, exist_ok=True)
    _git(path, "init")
    _git(path, "config", "user.email", "t@t")
    _git(path, "config", "user.name", "T")
    _git(path, "config", "commit.gpgsign", "false")
    _git(path, "commit", "--allow-empty", "-m", "init")


def test_commit_morning_report_succeeds_when_staged(tmp_path: Path):
    """When ``lifecycle/morning-report.md`` is staged, the function commits
    and emits MORNING_REPORT_COMMIT_RESULT with outcome=committed."""
    from cortex_command.overnight import events
    from cortex_command.overnight.runner import (
        _commit_morning_report_in_repo,
    )

    repo = tmp_path / "repo"
    _init_repo(repo)

    # Write the tracked top-level morning report and stage it. This mirrors
    # the runtime sequence: _generate_morning_report writes the file, then
    # _commit_morning_report_in_repo stages + commits it.
    lifecycle_dir = repo / "lifecycle"
    lifecycle_dir.mkdir(parents=True)
    (lifecycle_dir / "morning-report.md").write_text(
        "# Morning report\n\nGenerated by test fixture.\n"
    )
    _git(repo, "add", "lifecycle/morning-report.md")

    events_path = tmp_path / "overnight-events.log"

    _commit_morning_report_in_repo(repo, "test-session", events_path)

    # Verify the commit landed.
    log = _git(repo, "log", "--pretty=%s").stdout
    assert "Overnight session test-session: morning report" in log, (
        f"expected commit subject not found in log:\n{log}"
    )

    # Verify the success event was written. Per task 10's discovery, the
    # field name in events.log_event output is ``event``, not ``type``.
    assert events_path.exists(), (
        f"events log was never written at {events_path}"
    )
    matched = False
    for line in events_path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            evt = json.loads(line)
        except json.JSONDecodeError:
            continue
        if evt.get("event") == events.MORNING_REPORT_COMMIT_RESULT:
            assert evt.get("details", {}).get("outcome") == "committed", (
                f"expected outcome=committed, got: {evt!r}"
            )
            matched = True
            break
    assert matched, (
        f"no event with event={events.MORNING_REPORT_COMMIT_RESULT!r} found "
        f"in {events_path}; contents:\n{events_path.read_text()}"
    )


def test_commit_morning_report_noops_when_nothing_staged(tmp_path: Path):
    """When nothing is staged, the function returns early without emitting
    any morning-report event.

    Implementer choice (documented per spec Task 12): the no-op path in
    ``_commit_morning_report_in_repo`` returns immediately after the
    ``git diff --cached --quiet`` precheck succeeds (returncode == 0), so
    no event is written. This test asserts the events log either does not
    exist or contains no MORNING_REPORT_COMMIT_RESULT/FAILED lines.
    """
    from cortex_command.overnight import events
    from cortex_command.overnight.runner import (
        _commit_morning_report_in_repo,
    )

    repo = tmp_path / "repo"
    _init_repo(repo)

    # Deliberately do NOT write or stage lifecycle/morning-report.md. The
    # function will run ``git add lifecycle/morning-report.md`` (no-op,
    # path doesn't exist), then ``git diff --cached --quiet`` returns 0,
    # then the function returns without emitting an event.

    events_path = tmp_path / "overnight-events.log"

    _commit_morning_report_in_repo(repo, "test-session", events_path)

    # Verify no commit landed beyond the initial empty commit.
    log = _git(repo, "log", "--pretty=%s").stdout.strip().splitlines()
    assert log == ["init"], (
        f"expected only the initial commit; got log:\n{log}"
    )

    # Verify no morning-report event was written. The events log file
    # itself may or may not exist (the function never writes to it on the
    # no-op path); both states satisfy the no-op contract.
    if events_path.exists():
        for line in events_path.read_text().splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                evt = json.loads(line)
            except json.JSONDecodeError:
                continue
            assert evt.get("event") not in (
                events.MORNING_REPORT_COMMIT_RESULT,
                events.MORNING_REPORT_COMMIT_FAILED,
            ), (
                f"unexpected morning-report event on no-op path: {evt!r}"
            )
