"""Reverse-direction golden — old readers over machine-written mixed logs.

Spec 374 R16 (arm h). Phase 4 (phase-authority cutover, ADR-0025) forfeits the
cheap prose-side git-revert rollback; the STANDING safety net is that OLD READERS
keep working when they encounter machine-written logs. This golden pins that
guarantee: machine-written **mixed** logs (legacy transition rows —
``lifecycle_start`` / ``phase_transition`` / ``review_verdict`` / approvals /
terminal events — interleaved with the additive machine rows ``advance_started`` /
``advance_committed`` and the additive ``invocation_id`` field the ``advance``
dual-emission carries) are fed to the enumerated legacy reducer consumers, and
each reader's projection is asserted to stay CORRECT. This is the "reverse
direction": new writer, old reader.

The enumerated reader set is pinned in the fixture-directory README (see
FIXTURE_DIR below) and re-derived by grep here
(:func:`enumerate_reader_sites`) so the list stays honest. Prose-embedded readers
are explicitly NOT covered by this golden — their compatibility surface is the
served envelope's legacy display-phase projection field (coherence req 1), stated
in the fixture README.

"Correct legacy-phase projection" means the ACTUAL current behavior after Task 17
migrated three of these readers to the events-first shared resolver
(``common.resolve_lifecycle_phase``): where machine rows exist, the events-derived
state is authoritative; the statusline keeps its own artifact-only derivation (a
permanent, parity-pinned exception), so a mixed log can legitimately project
DIFFERENTLY between the events-first Python readers and the statusline (the
``rev-rework-events-only`` case pins exactly that divergence).

Anti-self-seal note: the ``*.resolver.phase`` / ``*.state.stdout`` / etc.
expected files are HAND-AUTHORED oracles reasoned from the documented legacy
ladder — NOT regenerated by running the readers. Independently, every case is
also checked with its additive machine content STRIPPED
(:func:`_strip_additive`): each reader's projection over the mixed log must equal
its projection over the additive-free legacy log, proving the additive rows and
the ``invocation_id`` field are inert (not merely that the reader agrees with
itself).
"""

from __future__ import annotations

import io
import json
import re
import subprocess
from pathlib import Path

import pytest

from cortex_command.lifecycle import counters as counters_mod
from cortex_command.lifecycle import state_cli as state_cli_mod
from cortex_command.dashboard.data import parse_feature_events
from cortex_command.backlog import generate_index
from cortex_command.hooks import scan_lifecycle as scan_lifecycle_mod

from tests._hook_fixture_helpers import extract_additional_context
from tests.test_lifecycle_phase_parity import _invoke_statusline_ladder

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "cortex-lifecycle-reverse"


# ---------------------------------------------------------------------------
# Enumerated reader set (build-time grep — spec R16 "enumerated by grep")
# ---------------------------------------------------------------------------
#
# (label, repo-relative reader path, sentinel symbol proving it is a
# reducer/resolver consumer of events.log). The fixture README pins the same
# set; ``test_readme_pins_enumerated_readers`` asserts this table, the README,
# and the live source agree — so a reader that drops its resolver/reducer call,
# or a README that drops a reader, fails CI.
ENUMERATED_READERS: tuple[tuple[str, str, str], ...] = (
    ("cortex-lifecycle-state", "cortex_command/lifecycle/state_cli.py", "reduce_lifecycle_state"),
    ("cortex-lifecycle-counters", "cortex_command/lifecycle/counters.py", "count_rework_cycles"),
    ("statusline derivation", "claude/statusline.sh", "detect_lifecycle_phase"),
    ("dashboard/data.py", "cortex_command/dashboard/data.py", "resolve_lifecycle_phase"),
    ("scan_lifecycle", "cortex_command/hooks/scan_lifecycle.py", "resolve_lifecycle_phase"),
    ("generate_index.py", "cortex_command/backlog/generate_index.py", "resolve_lifecycle_phase"),
)


def enumerate_reader_sites() -> list[tuple[str, str, int, str]]:
    """Grep each enumerated reader for its sentinel; return (label, path, lineno, line).

    Deterministic recapture harness for the README's reader table: run this and
    paste the ``path:lineno`` values. Fails loudly if a sentinel vanished from a
    reader (the reader stopped consuming the shared resolver/reducer).
    """
    sites: list[tuple[str, str, int, str]] = []
    for label, rel, sentinel in ENUMERATED_READERS:
        text = (REPO_ROOT / rel).read_text(encoding="utf-8")
        hit = None
        for lineno, line in enumerate(text.splitlines(), start=1):
            if sentinel in line:
                hit = (lineno, line.strip())
                break
        assert hit is not None, (
            f"reader {label} ({rel}) no longer references sentinel {sentinel!r} "
            f"— the enumerated reader set is stale, re-derive it"
        )
        sites.append((label, rel, hit[0], hit[1]))
    return sites


# ---------------------------------------------------------------------------
# Fixture discovery + staging
# ---------------------------------------------------------------------------

CASES: list[str] = sorted(
    p.name[: -len(".events.log")] for p in FIXTURE_DIR.glob("*.events.log")
)

# events the advance dual-emission adds on top of the legacy vocabulary; the
# reverse golden proves these are inert to every old reader.
_ADDITIVE_EVENTS = frozenset({"advance_started", "advance_committed"})


def _read(case: str, suffix: str) -> str | None:
    p = FIXTURE_DIR / f"{case}.{suffix}"
    return p.read_text(encoding="utf-8") if p.is_file() else None


def _strip_additive(log_text: str) -> str:
    """Return the log with additive machine content removed.

    Drops every ``advance_started`` / ``advance_committed`` row and strips the
    additive ``invocation_id`` field from the surviving (legacy-vocabulary) rows,
    reconstructing the pre-cutover legacy log. Torn/unparseable lines pass through
    verbatim so the tolerant-reader behavior is preserved. Used only by the
    inertness differential — never to build the pinned expectations.
    """
    out: list[str] = []
    for raw in log_text.splitlines():
        line = raw.strip()
        if not line:
            out.append(raw)
            continue
        try:
            ev = json.loads(line)
        except json.JSONDecodeError:
            out.append(raw)  # torn line — keep verbatim
            continue
        if isinstance(ev, dict) and ev.get("event") in _ADDITIVE_EVENTS:
            continue
        if isinstance(ev, dict) and "invocation_id" in ev:
            ev = {k: v for k, v in ev.items() if k != "invocation_id"}
            out.append(json.dumps(ev))
        else:
            out.append(raw)
    return "".join(s + "\n" for s in out)


def _stage(case: str, tmp_path: Path, *, log_text: str | None = None) -> tuple[Path, Path, str]:
    """Stage a scratch repo for ``case``; return (repo_root, lifecycle_dir, slug).

    The slug is the fixture basename (a synthetic ``rev-*`` name that never
    exists in the real ``cortex/lifecycle/`` tree). ``log_text`` overrides the
    staged events.log (used by the inertness differential); otherwise the
    fixture ``.events.log`` is staged verbatim.
    """
    slug = case
    repo = tmp_path / "repo"
    lifecycle_dir = repo / "cortex" / "lifecycle"
    fdir = lifecycle_dir / slug
    fdir.mkdir(parents=True, exist_ok=True)

    events = log_text if log_text is not None else _read(case, "events.log")
    assert events is not None, f"{case}.events.log missing"
    (fdir / "events.log").write_text(events, encoding="utf-8")

    for suffix, dest in (
        ("research.md", "research.md"),
        ("spec.md", "spec.md"),
        ("plan.md", "plan.md"),
        ("review.md", "review.md"),
    ):
        content = _read(case, suffix)
        if content is not None:
            (fdir / dest).write_text(content, encoding="utf-8")

    return repo, lifecycle_dir, slug


# ---------------------------------------------------------------------------
# Per-reader invocation seams (each drives the REAL reader code path)
# ---------------------------------------------------------------------------


def _run_state_cli(
    repo: Path, slug: str, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> tuple[str, str]:
    """cortex-lifecycle-state reader — returns (stdout, stderr)."""
    monkeypatch.chdir(repo)
    with pytest.raises(SystemExit) as exc:
        state_cli_mod.main(["--feature", slug])
    assert exc.value.code == 0
    cap = capsys.readouterr()
    return cap.out, cap.err


def _run_counters(
    lifecycle_dir: Path, slug: str, capsys: pytest.CaptureFixture[str]
) -> str:
    """cortex-lifecycle-counters reader — returns stdout."""
    rc = counters_mod.main(["--feature", slug, "--lifecycle-dir", str(lifecycle_dir)])
    assert rc == 0
    return capsys.readouterr().out


def _run_dashboard(lifecycle_dir: Path, slug: str) -> str | None:
    """dashboard/data.py reader — returns the resolver-derived current_phase."""
    return parse_feature_events(slug, lifecycle_dir)["current_phase"]


def _run_generate_index(repo: Path, lifecycle_dir: Path, slug: str) -> str | None:
    """generate_index.py reader — stage a backlog item pointing at slug, return
    the item's resolver-derived lifecycle_phase (base phase, -paused stripped)."""
    backlog_dir = repo / "cortex" / "backlog"
    backlog_dir.mkdir(parents=True, exist_ok=True)
    (backlog_dir / f"9001-{slug}.md").write_text(
        f"---\nid: 9001\ntitle: Reverse golden probe\nstatus: ready\n"
        f"lifecycle_slug: {slug}\n---\n\nprobe body\n",
        encoding="utf-8",
    )
    active_items, _active_ids, _archive_ids, _all_items = generate_index.collect_items(
        backlog_dir=backlog_dir, lifecycle_dir=lifecycle_dir
    )
    matches = [it for it in active_items if it["id"] == 9001]
    assert matches, "backlog probe item not collected"
    return matches[0]["lifecycle_phase"]


def _run_scan_lifecycle(
    repo: Path, slug: str, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> str:
    """scan_lifecycle reader — drive main() end-to-end, return additionalContext.

    Single incomplete feature + no session match → the hook crash-recovery
    claims it active and renders its phase label; a terminal feature is
    suppressed and the hook emits nothing (additionalContext == "").
    """
    payload = {"hook_event_name": "SessionStart", "session_id": "REV-SID", "cwd": str(repo)}
    env_file = repo / ".claude-env"
    env_file.write_text("", encoding="utf-8")
    monkeypatch.setenv("CLAUDE_ENV_FILE", str(env_file))
    monkeypatch.delenv("LIFECYCLE_SESSION_ID", raising=False)
    monkeypatch.setenv("CORTEX_SCAN_LIFECYCLE_STALE_DAYS", "0")
    monkeypatch.setattr("sys.stdin", io.StringIO(json.dumps(payload)))
    rc = scan_lifecycle_mod.main()
    assert rc == 0
    return extract_additional_context(capsys.readouterr().out)


def _run_statusline(lifecycle_dir: Path, slug: str) -> str:
    """statusline.sh reader — invoke the bash phase ladder against the staged dir.

    The statusline is a bash reader and a permanent artifact-derivation exception
    (it is NOT migrated to the events-first resolver). It is exercised
    deterministically here by sourcing its phase-detection ladder fragment
    (shared with the parity harness in ``tests.test_lifecycle_phase_parity``)
    against the staged feature dir — not covered only-by-proxy.
    """
    return _invoke_statusline_ladder(lifecycle_dir / slug).strip()


# ---------------------------------------------------------------------------
# Golden assertions
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", CASES)
def test_state_cli_projection(case, tmp_path, monkeypatch, capsys):
    repo, _lc, slug = _stage(case, tmp_path)
    out, err = _run_state_cli(repo, slug, monkeypatch, capsys)
    assert out == _read(case, "state.stdout")
    assert err == (_read(case, "state.stderr") or "")


@pytest.mark.parametrize("case", CASES)
def test_counters_projection(case, tmp_path, capsys):
    _repo, lc, slug = _stage(case, tmp_path)
    assert _run_counters(lc, slug, capsys) == _read(case, "counters.stdout")


@pytest.mark.parametrize("case", CASES)
def test_dashboard_projection(case, tmp_path):
    _repo, lc, slug = _stage(case, tmp_path)
    assert _run_dashboard(lc, slug) == _read(case, "resolver.phase").strip()


@pytest.mark.parametrize("case", CASES)
def test_generate_index_projection(case, tmp_path):
    repo, lc, slug = _stage(case, tmp_path)
    expected = _read(case, "resolver.phase").strip().removesuffix("-paused")
    assert _run_generate_index(repo, lc, slug) == expected


@pytest.mark.parametrize("case", CASES)
def test_statusline_projection(case, tmp_path):
    _repo, lc, slug = _stage(case, tmp_path)
    assert _run_statusline(lc, slug) == _read(case, "statusline.phase").strip()


@pytest.mark.parametrize("case", CASES)
def test_scan_lifecycle_projection(case, tmp_path, monkeypatch, capsys):
    repo, _lc, slug = _stage(case, tmp_path)
    ctx = _run_scan_lifecycle(repo, slug, monkeypatch, capsys)
    contains = (_read(case, "scan.contains") or "").splitlines()
    if not contains:
        assert ctx == "", f"{case}: expected scan suppression, got: {ctx!r}"
    else:
        for needle in contains:
            assert needle in ctx, f"{case}: {needle!r} not in scan additionalContext:\n{ctx}"


# ---------------------------------------------------------------------------
# Inertness differential (anti-self-seal): mixed-log projection == additive-free
# legacy-log projection, for every reader. Independent of the pinned oracles.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", CASES)
def test_additive_rows_are_inert(case, tmp_path, monkeypatch, capsys):
    mixed = _read(case, "events.log")
    stripped = _strip_additive(mixed)
    # Sanity: stripping actually removed additive content for the machine cases.
    assert stripped != mixed or "advance_" not in mixed

    def projections(log_text: str, sub: Path):
        repo, lc, slug = _stage(case, sub, log_text=log_text)
        state_out, state_err = _run_state_cli(repo, slug, monkeypatch, capsys)
        return {
            "state_out": state_out,
            "counters": _run_counters(lc, slug, capsys),
            "dashboard": _run_dashboard(lc, slug),
            "generate_index": _run_generate_index(repo, lc, slug),
            "statusline": _run_statusline(lc, slug),
        }

    mixed_proj = projections(mixed, tmp_path / "mixed")
    legacy_proj = projections(stripped, tmp_path / "legacy")
    assert mixed_proj == legacy_proj, (
        f"{case}: additive machine content changed a legacy projection\n"
        f"  mixed  = {mixed_proj}\n  legacy = {legacy_proj}"
    )


# ---------------------------------------------------------------------------
# Reader-list honesty
# ---------------------------------------------------------------------------


def test_reader_sentinels_present():
    """Every enumerated reader still calls its shared resolver/reducer sentinel."""
    sites = enumerate_reader_sites()
    assert len(sites) == len(ENUMERATED_READERS)


def test_readme_pins_enumerated_readers():
    """The fixture README enumerates exactly the grepped reader set, and states
    the prose-embedded-readers carve-out."""
    readme = (FIXTURE_DIR / "README.md").read_text(encoding="utf-8")
    for label, rel, _sentinel in ENUMERATED_READERS:
        assert label in readme, f"README missing reader label {label!r}"
        assert rel in readme, f"README missing reader path {rel!r}"
    # Prose-embedded readers explicitly out of scope (coherence req 1).
    assert "prose-embedded" in readme.lower()
    assert "legacy display-phase projection" in readme.lower()
