"""Fast-path template-correctness assertions for sub-agent dispatch sites.

This test asserts pure string properties of the three canonical dispatch
templates after the path+SHA migration (see
``lifecycle/reduce-sub-agent-dispatch-artifact-duplication/spec.md``,
Requirement 10). No live model calls, no slow-marker — this is the
spec-encoded checklist that drives Tasks 4–10 (the template edits).

Templates are read from CANONICAL sources at ``skills/``, NOT from
``plugins/cortex-core/skills/`` mirrors (mirrors are regenerated by the
pre-commit hook and validated separately by
``tests/test_dual_source_reference_parity.py``).

Assertions, grouped by Requirement number for failure→spec traceability:

Requirement 10(a) — inline-content placeholders ABSENT:
  - ``{artifact content}`` absent from ``skills/critical-review/SKILL.md``.
  - ``{full contents of lifecycle/{feature}/spec.md}`` and
    ``{full contents of lifecycle/{feature}/research.md}`` absent from
    ``skills/lifecycle/references/plan.md``.
  - ``{contents of lifecycle/{feature}/spec.md, or a summary with a path to
    read it}`` absent from ``skills/lifecycle/references/review.md``.

Requirement 10(b) — path/SHA placeholders PRESENT at expected sites:
  - ``{artifact_path}`` and ``{artifact_sha256}`` present ≥3× each in
    ``skills/critical-review/SKILL.md`` (reviewer prompt, fallback
    single-agent prompt, synthesizer prompt — Requirements 1–3).
  - ``{spec_path}`` and ``{research_path}`` present in
    ``skills/lifecycle/references/plan.md`` (Requirement 6).
  - ``{spec_path}`` present in ``skills/lifecycle/references/review.md``
    (Requirement 7).

Requirement 10(c) — reviewer sentinel directive present VERBATIM:
  - ``skills/critical-review/SKILL.md`` reviewer prompt sections contain
    the verbatim string ``READ_OK: <path> <sha>``.

Requirement 10(d) — synthesizer sentinel directive present VERBATIM:
  - ``skills/critical-review/SKILL.md`` synthesizer prompt section contains
    the verbatim string ``SYNTH_READ_OK: <path> <sha>``.
"""

from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

CRITICAL_REVIEW_SKILL = REPO_ROOT / "skills" / "critical-review" / "SKILL.md"
LIFECYCLE_PLAN = REPO_ROOT / "skills" / "lifecycle" / "references" / "plan.md"
LIFECYCLE_REVIEW = REPO_ROOT / "skills" / "lifecycle" / "references" / "review.md"


def _read(path: Path) -> str:
    assert path.exists(), f"Canonical template missing: {path}"
    return path.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Requirement 10(a): inline-content placeholders absent
# ---------------------------------------------------------------------------


def test_req10a_critical_review_no_artifact_content_placeholder() -> None:
    """`{artifact content}` MUST be absent from critical-review SKILL.md."""
    content = _read(CRITICAL_REVIEW_SKILL)
    assert "{artifact content}" not in content, (
        "Req 10(a): '{artifact content}' must not appear in "
        f"{CRITICAL_REVIEW_SKILL.relative_to(REPO_ROOT)} after the path+SHA "
        "migration (Req 1/2/3)."
    )


def test_req10a_lifecycle_plan_no_full_contents_placeholders() -> None:
    """`{full contents of lifecycle/{feature}/spec.md}` and the research
    counterpart MUST be absent from lifecycle plan.md."""
    content = _read(LIFECYCLE_PLAN)
    assert "{full contents of lifecycle/{feature}/spec.md}" not in content, (
        "Req 10(a): '{full contents of lifecycle/{feature}/spec.md}' must "
        f"not appear in {LIFECYCLE_PLAN.relative_to(REPO_ROOT)} (Req 6)."
    )
    assert "{full contents of lifecycle/{feature}/research.md}" not in content, (
        "Req 10(a): '{full contents of lifecycle/{feature}/research.md}' "
        f"must not appear in {LIFECYCLE_PLAN.relative_to(REPO_ROOT)} "
        "(Req 6)."
    )


def test_req10a_lifecycle_review_no_hedged_contents_placeholder() -> None:
    """`{contents of lifecycle/{feature}/spec.md, or a summary with a path
    to read it}` MUST be absent from lifecycle review.md."""
    content = _read(LIFECYCLE_REVIEW)
    needle = (
        "{contents of lifecycle/{feature}/spec.md, or a summary with a "
        "path to read it}"
    )
    assert needle not in content, (
        "Req 10(a): hedged-contents placeholder must not appear in "
        f"{LIFECYCLE_REVIEW.relative_to(REPO_ROOT)} (Req 7)."
    )


# ---------------------------------------------------------------------------
# Requirement 10(b): path/SHA placeholders present at expected sites
# ---------------------------------------------------------------------------


def test_req10b_critical_review_artifact_path_placeholder_present() -> None:
    """`{artifact_path}` MUST appear ≥3× in critical-review SKILL.md
    (reviewer + fallback + synthesizer)."""
    content = _read(CRITICAL_REVIEW_SKILL)
    count = content.count("{artifact_path}")
    assert count >= 3, (
        f"Req 10(b): '{{artifact_path}}' must appear ≥3 times in "
        f"{CRITICAL_REVIEW_SKILL.relative_to(REPO_ROOT)} (reviewer, "
        f"fallback single-agent, synthesizer); found {count}."
    )


def test_req10b_critical_review_artifact_sha256_placeholder_present() -> None:
    """`{artifact_sha256}` MUST appear ≥3× in critical-review SKILL.md."""
    content = _read(CRITICAL_REVIEW_SKILL)
    count = content.count("{artifact_sha256}")
    assert count >= 3, (
        f"Req 10(b): '{{artifact_sha256}}' must appear ≥3 times in "
        f"{CRITICAL_REVIEW_SKILL.relative_to(REPO_ROOT)}; found {count}."
    )


def test_req10b_lifecycle_plan_spec_and_research_path_placeholders_present() -> None:
    """`{spec_path}` and `{research_path}` MUST appear in lifecycle plan.md."""
    content = _read(LIFECYCLE_PLAN)
    assert "{spec_path}" in content, (
        f"Req 10(b): '{{spec_path}}' must appear in "
        f"{LIFECYCLE_PLAN.relative_to(REPO_ROOT)} (Req 6)."
    )
    assert "{research_path}" in content, (
        f"Req 10(b): '{{research_path}}' must appear in "
        f"{LIFECYCLE_PLAN.relative_to(REPO_ROOT)} (Req 6)."
    )


def test_req10b_lifecycle_review_spec_path_placeholder_present() -> None:
    """`{spec_path}` MUST appear in lifecycle review.md."""
    content = _read(LIFECYCLE_REVIEW)
    assert "{spec_path}" in content, (
        f"Req 10(b): '{{spec_path}}' must appear in "
        f"{LIFECYCLE_REVIEW.relative_to(REPO_ROOT)} (Req 7)."
    )


# ---------------------------------------------------------------------------
# Requirement 10(c): reviewer READ_OK sentinel directive verbatim
# ---------------------------------------------------------------------------


def test_req10c_reviewer_prompt_contains_read_ok_sentinel_directive() -> None:
    """The verbatim sentinel format `READ_OK: <path> <sha>` MUST appear in
    critical-review SKILL.md reviewer prompt sections (Req 1)."""
    content = _read(CRITICAL_REVIEW_SKILL)
    assert "READ_OK: <path> <sha>" in content, (
        "Req 10(c): verbatim 'READ_OK: <path> <sha>' must appear in "
        f"{CRITICAL_REVIEW_SKILL.relative_to(REPO_ROOT)} reviewer prompt "
        "(Req 1)."
    )


# ---------------------------------------------------------------------------
# Requirement 10(d): synthesizer SYNTH_READ_OK directive verbatim
# ---------------------------------------------------------------------------


def test_req10d_synthesizer_prompt_contains_synth_read_ok_directive() -> None:
    """The verbatim sentinel `SYNTH_READ_OK: <path> <sha>` MUST appear in
    critical-review SKILL.md synthesizer prompt section (Req 3)."""
    content = _read(CRITICAL_REVIEW_SKILL)
    assert "SYNTH_READ_OK: <path> <sha>" in content, (
        "Req 10(d): verbatim 'SYNTH_READ_OK: <path> <sha>' must appear in "
        f"{CRITICAL_REVIEW_SKILL.relative_to(REPO_ROOT)} synthesizer "
        "prompt (Req 3)."
    )
