"""Reference-size ratchet (#408) — down-only per-directory byte pins.

Enforces the verb-first size direction for reference prose
(cortex/requirements/project.md, Architectural Constraints): every
``references/`` directory under ``skills/`` and ``plugins/*/skills/`` carries
a ``size-pin.txt`` byte pin. Content at or below the pin passes; growth fails
with a pointer to the verb-first rule; lowering a pin is always allowed and
expected (``just ratchet-refs`` seeds missing pins and lowers stale ones,
never raises). Raising a pin is a hand edit that must carry an annotated
``# raised: <reason >=30 chars>, lifecycle-id=<NNN>, date=<YYYY-MM-DD>`` line,
mirroring the SKILL.md size-budget-exception marker.

Named evidence (the enforcement-gates constraint): the corpus reached 58
files / ~241KB of net-addition reference commits against the stated ~10x
reduction direction, and no test could see reference growth — SKILL.md bodies
had a 500-line budget test while references had nothing.

Enumeration is canonical-first with content-hash dedupe, so rsync mirrors
regenerated by ``just build-plugin`` collapse onto their canonical dirs and a
breach reports once; plugin-only canonical dirs (pr-review, ui-brief, the
android skills) are ratcheted in their own right. ``cortex_command/pipeline/
prompts`` joins the enumeration too (#455, requirement 16) — review-shaping
prose loaded like reference prose, pinned so it has no unmeasured hiding place.

Shared logic lives in ``scripts/ratchet_refs.py`` (also the ``--write``
affordance) so the test and the recipe cannot drift. Regression fixtures
under ``tests/fixtures/reference_size_ratchet/`` (outside the enumerated
globs) pin each failure path: growth breach, missing pin, malformed pin
value, and an invalid raised-marker. All findings aggregate into a single
multi-line ``AssertionError`` (no fail-fast).
"""

from __future__ import annotations

import shutil
import sys

import pytest

from conftest import repo_root

sys.path.insert(0, str(repo_root() / "scripts"))

import ratchet_refs  # noqa: E402


FIXTURES_ROOT = repo_root() / "tests" / "fixtures" / "reference_size_ratchet"


def test_all_reference_dirs_within_pins() -> None:
    """Every unique references directory has a well-formed pin and is at or
    below it. Findings aggregate into one AssertionError."""
    all_errors: list[str] = []
    for directory in ratchet_refs.enumerate_reference_dirs(repo_root()):
        all_errors.extend(ratchet_refs.classify(directory))

    if all_errors:
        raise AssertionError(
            f"{len(all_errors)} reference-size ratchet violation(s):\n"
            + "\n".join(f"  {e}" for e in all_errors)
        )


def test_regression_growth_breach() -> None:
    """Content above the pin trips the growth path: measured vs pin bytes and
    the verb-first pointer must both appear."""
    fixture = FIXTURES_ROOT / "growth-breach" / "references"
    assert fixture.exists(), fixture
    errors = ratchet_refs.classify(fixture)
    assert len(errors) == 1, errors
    assert "exceeds its pin of 50" in errors[0]
    assert "verb-first" in errors[0]


def test_regression_missing_pin() -> None:
    """A references directory with no size-pin.txt trips the seeding path,
    naming the measured size and the `just ratchet-refs` affordance."""
    fixture = FIXTURES_ROOT / "missing-pin" / "references"
    assert fixture.exists(), fixture
    errors = ratchet_refs.classify(fixture)
    assert len(errors) == 1, errors
    assert "has no size-pin.txt" in errors[0]
    assert "just ratchet-refs" in errors[0]


def test_regression_malformed_pin_value() -> None:
    """A pin file whose first line is not an integer byte count is malformed,
    not silently treated as unpinned."""
    fixture = FIXTURES_ROOT / "malformed-pin" / "references"
    assert fixture.exists(), fixture
    errors = ratchet_refs.classify(fixture)
    assert len(errors) == 1, errors
    assert "first line must be an integer byte count" in errors[0]


def test_regression_invalid_raise_marker() -> None:
    """A '# raised:' line whose rationale is under 30 chars fails the marker
    regex and is reported as invalid — proving the format boundary holds."""
    fixture = FIXTURES_ROOT / "invalid-raise-marker" / "references"
    assert fixture.exists(), fixture
    errors = ratchet_refs.classify(fixture)
    assert len(errors) == 1, errors
    assert "invalid raised-marker" in errors[0]


def test_regression_valid_raise_marker_passes() -> None:
    """A well-formed raise annotation is a legitimate exception: the pin file
    parses clean and content at the raised pin passes."""
    fixture = FIXTURES_ROOT / "valid-raise-marker" / "references"
    assert fixture.exists(), fixture
    assert ratchet_refs.classify(fixture) == []


def test_pin_file_excluded_from_measurement() -> None:
    """The pin file's own bytes never count toward the measured size — the
    valid-raise-marker fixture's content equals its pin exactly, which only
    holds if size-pin.txt is excluded."""
    fixture = FIXTURES_ROOT / "valid-raise-marker" / "references"
    measured = ratchet_refs.measure(fixture)
    pin, errors = ratchet_refs.parse_pin(fixture)
    assert errors == []
    assert measured == pin


def test_fixtures_outside_enumerated_globs() -> None:
    """The regression fixtures must never leak into the repo-wide
    enumeration — they live under tests/fixtures/, which the canonical and
    plugin globs do not reach."""
    enumerated = ratchet_refs.enumerate_reference_dirs(repo_root())
    assert not any(FIXTURES_ROOT in d.parents for d in enumerated), enumerated


def test_mirror_dirs_deduplicate() -> None:
    """In-sync rsync mirrors collapse onto their canonical dir: no two
    enumerated directories share a content hash, and the canonical
    skills/<name>/references path is the surviving representative when a
    plugin mirror of the same skill exists."""
    enumerated = ratchet_refs.enumerate_reference_dirs(repo_root())
    hashes = [ratchet_refs._dir_content_hash(d) for d in enumerated]
    assert len(hashes) == len(set(hashes))

    canonical_names = {
        d.parent.name for d in enumerated if d.parent.parent == repo_root() / "skills"
    }
    plugin_names = {
        d.parent.name
        for d in enumerated
        if d.parent.parent != repo_root() / "skills"
    }
    # The prompts dir partitions as `pipeline` (its parent is
    # cortex_command/, not skills/). There is no skills/pipeline/, so it
    # introduces no overlap — asserted rather than left incidental.
    assert "pipeline" in plugin_names, sorted(plugin_names)
    assert not (repo_root() / "skills" / "pipeline").exists()

    overlap = canonical_names & plugin_names
    assert not overlap, (
        f"plugin references dirs surviving dedupe despite a canonical twin "
        f"(mirror drift — run `just build-plugin`): {sorted(overlap)}"
    )


PROMPTS_DIR = repo_root() / "cortex_command" / "pipeline" / "prompts"


def test_pipeline_prompts_enumerated_and_pinned() -> None:
    """Requirement 16 — review-shaping prose has no unmeasured hiding place:
    cortex_command/pipeline/prompts is enumerated by the ratchet and sits at
    or below its own pin."""
    enumerated = ratchet_refs.enumerate_reference_dirs(repo_root())
    assert PROMPTS_DIR in enumerated, [str(d) for d in enumerated]
    assert ratchet_refs.classify(PROMPTS_DIR) == []


def test_pipeline_prompts_missing_pin_is_reported(tmp_path) -> None:
    """The pin is load-bearing, not decorative: a copy of the real prompts
    directory with size-pin.txt removed trips classify's missing-pin path."""
    copied = tmp_path / "prompts"
    shutil.copytree(PROMPTS_DIR, copied)
    assert ratchet_refs.classify(copied) == []

    (copied / ratchet_refs.PIN_FILENAME).unlink()
    errors = ratchet_refs.classify(copied)
    assert len(errors) == 1, errors
    assert "has no size-pin.txt" in errors[0]
    assert "just ratchet-refs" in errors[0]


def test_lowering_a_pin_preserves_its_raised_provenance(tmp_path) -> None:
    """Lowering must not erase the `# raised:` lines.

    Lowering is the ratchet's common operation, and rewriting the pin file as a
    bare byte count wiped the provenance `parse_pin` validates. Observed
    2026-08-07 (#455): one `just ratchet-refs` took skills/build/references/
    from two markers to zero, breaking the same lifecycle's own acceptance
    criterion that the `# raised:` count was unchanged.
    """
    fixture = FIXTURES_ROOT / "valid-raise-marker" / "references"
    copied = tmp_path / "references"
    shutil.copytree(fixture, copied)

    pin_path = copied / ratchet_refs.PIN_FILENAME
    original = pin_path.read_text(encoding="utf-8").splitlines()
    markers = [line for line in original[1:] if line.startswith("# raised:")]
    assert markers, "fixture must carry at least one raised marker"

    # Shrink the measured content so the next write takes the lowering branch.
    content = sorted(p for p in copied.iterdir() if p.name != ratchet_refs.PIN_FILENAME)
    content[0].write_text("", encoding="utf-8")
    lowered = ratchet_refs.measure(copied)
    assert lowered < int(original[0]), "content must actually shrink"

    ratchet_refs._write_pin(pin_path, lowered)

    rewritten = pin_path.read_text(encoding="utf-8").splitlines()
    assert rewritten[0] == str(lowered), "byte count must be updated"
    assert rewritten[1:] == original[1:], "provenance lines must survive verbatim"
    assert ratchet_refs.classify(copied) == [], "the rewritten pin must still parse"
