"""Snapshot test pinning the wire contract of ``bin/cortex-backlog-ready``.

Constructs a deterministic fixture backlog directory in ``tmp_path``
covering every spec R6/R7 contract path:

  - All five canonical priorities (``critical``, ``high``, ``medium``,
    ``low``, ``contingent``), with ``low`` empty to verify the
    ``"items": []`` schema.
  - Two ``status: refined`` items (different priorities) to verify
    refined-first within-group ordering.
  - One item with an external (non-digit, non-UUID) blocker to verify
    the warning path keeps the item out of ``groups`` but surfaces it
    in ``ineligible`` when ``--include-blocked`` is passed.
  - One item with an internal non-terminal blocker to verify the
    ``"blocked by non-terminal internal blocker"`` reason path.
  - One terminal-status item (``status: complete``) plus an active item
    whose only blocker points to it. The active item must classify as
    ready (regression guard for the bug fixed in ticket 152: the script
    must scan ``.md`` files for the full corpus, not rely on
    ``index.json`` which filters terminal items out).

The snapshot is regenerated by running the script once against the
fixture; subsequent edits update the test setup and the fixture in
lockstep. ``index.json`` is constructed directly (not via
``cortex-generate-backlog-index``) to keep the test self-contained.
``index.json`` excludes the terminal-status record (mirroring real
``collect_items()`` behavior) — that record only exists as a ``.md``
file so the script must hit the source-tree scan to resolve the
blocker.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "bin" / "cortex-backlog-ready"
FIXTURE = Path(__file__).resolve().parent / "fixtures" / "backlog_ready_render.json"


# Deterministic fixture records. Field set mirrors what
# ``cortex-generate-backlog-index`` emits (see ``backlog/index.json``)
# but pruned to the keys ``backlog/ready.py`` consumes:
# ``id``, ``title``, ``status``, ``priority``, ``type``, ``blocked_by``,
# ``parent``, ``uuid``.
_FIXTURE_RECORDS = [
    {
        "id": 1,
        "title": "critical refined",
        "status": "refined",
        "priority": "critical",
        "type": "feature",
        "blocked_by": [],
        "parent": None,
        "uuid": "00000000-0000-0000-0000-000000000001",
    },
    {
        "id": 2,
        "title": "critical backlog",
        "status": "backlog",
        "priority": "critical",
        "type": "feature",
        "blocked_by": [],
        "parent": None,
        "uuid": "00000000-0000-0000-0000-000000000002",
    },
    {
        "id": 3,
        "title": "high refined",
        "status": "refined",
        "priority": "high",
        "type": "feature",
        "blocked_by": [],
        "parent": None,
        "uuid": "00000000-0000-0000-0000-000000000003",
    },
    {
        "id": 4,
        "title": "high external-blocked",
        "status": "backlog",
        "priority": "high",
        "type": "feature",
        "blocked_by": ["anthropics/claude-code#999"],
        "parent": None,
        "uuid": "00000000-0000-0000-0000-000000000004",
    },
    {
        "id": 5,
        "title": "high backlog",
        "status": "backlog",
        "priority": "high",
        "type": "feature",
        "blocked_by": [],
        "parent": None,
        "uuid": "00000000-0000-0000-0000-000000000005",
    },
    {
        "id": 6,
        "title": "medium internal-blocked",
        "status": "backlog",
        "priority": "medium",
        "type": "feature",
        "blocked_by": ["7"],
        "parent": None,
        "uuid": "00000000-0000-0000-0000-000000000006",
    },
    {
        "id": 7,
        "title": "medium backlog",
        "status": "backlog",
        "priority": "medium",
        "type": "feature",
        "blocked_by": [],
        "parent": None,
        "uuid": "00000000-0000-0000-0000-000000000007",
    },
    {
        "id": 8,
        "title": "contingent backlog",
        "status": "backlog",
        "priority": "contingent",
        "type": "feature",
        "blocked_by": [],
        "parent": None,
        "uuid": "00000000-0000-0000-0000-000000000008",
    },
    {
        "id": 9,
        "title": "medium terminal",
        "status": "complete",
        "priority": "medium",
        "type": "feature",
        "blocked_by": [],
        "parent": None,
        "uuid": "00000000-0000-0000-0000-000000000009",
    },
    {
        "id": 10,
        "title": "medium blocked by terminal",
        "status": "backlog",
        "priority": "medium",
        "type": "feature",
        "blocked_by": ["9"],
        "parent": None,
        "uuid": "00000000-0000-0000-0000-000000000010",
    },
]


def _write_md(backlog_dir: Path, record: dict) -> None:
    """Write a minimal ``NNN-slug.md`` frontmatter file for *record*.

    The script reads ``index.json`` for its data, but the spec's
    stale-index check (R8) globs ``backlog/[0-9]*-*.md``; without these
    files the warning path never fires. They also model real-world
    layout so the test exercises the same load path as production.
    """
    slug = record["title"].replace(" ", "-")
    md_path = backlog_dir / f"{record['id']:03d}-{slug}.md"
    fm_lines = [
        "---",
        'schema_version: "1"',
        f"uuid: {record['uuid']}",
        f"id: {record['id']}",
        f'title: "{record["title"]}"',
        f"status: {record['status']}",
        f"priority: {record['priority']}",
        f"type: {record['type']}",
        f"blocked_by: {json.dumps(record['blocked_by'])}",
        f"parent: {json.dumps(record['parent'])}",
        "---",
        "",
    ]
    md_path.write_text("\n".join(fm_lines), encoding="utf-8")


def _build_fixture_backlog(tmp_path: Path) -> Path:
    """Materialize the fixture backlog under ``tmp_path / "backlog"``.

    All records are written as ``.md`` files (so the full-corpus scan
    sees terminal items). ``index.json`` excludes terminal-status
    records — mirroring ``collect_items()`` in
    ``backlog/generate_index.py``, which filters terminal items out
    before serialization. This composition forces the script to resolve
    the ``blocked_by: ["9"]`` reference via the source-tree scan rather
    than the index, exercising the ticket-152 fix.
    """
    backlog_dir = tmp_path / "backlog"
    backlog_dir.mkdir()
    for record in _FIXTURE_RECORDS:
        _write_md(backlog_dir, record)

    # index.json mirrors collect_items()'s active-only output.
    active_records = [r for r in _FIXTURE_RECORDS if r["status"] != "complete"]
    (backlog_dir / "index.json").write_text(
        json.dumps(active_records, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return backlog_dir


def _run_script(cwd: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [str(SCRIPT), *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=True,
    )


def test_backlog_ready_render_snapshot(tmp_path: Path) -> None:
    """Pin ``cortex-backlog-ready --include-blocked`` JSON output.

    The fixture covers the full R6 + R7 wire contract: all five
    priorities (low empty), refined-first ordering, an external
    blocker (ineligible/blocker), and an internal non-terminal blocker
    (ineligible/blocker via the partition_ready sentinel).
    """
    _build_fixture_backlog(tmp_path)

    result = _run_script(tmp_path, "--include-blocked")

    expected = FIXTURE.read_text(encoding="utf-8")
    assert result.stdout == expected, (
        "cortex-backlog-ready output drifted from snapshot at "
        f"{FIXTURE}. Re-run the script against the fixture and update "
        "the snapshot if the schema change is intentional."
    )
