#!/usr/bin/env python3
"""Reference-size ratchet — shared measurement, pin parsing, and pin writes.

Enforces the verb-first size direction for skills reference prose
(cortex/requirements/project.md, Architectural Constraints): every
``references/`` directory carries a ``size-pin.txt`` byte pin; content at or
below the pin passes, growth fails, and lowering the pin is always allowed
and expected. Raising a pin is a hand edit that must carry an annotated
``# raised:`` exception line (see RAISE_MARKER_REGEX).

Two consumers share this module:
  - ``tests/test_reference_size_ratchet.py`` — the enforcement gate.
  - ``just ratchet-refs`` → ``python3 scripts/ratchet_refs.py --write`` —
    the seed/lower affordance. Down-only: it seeds missing pins at current
    size and lowers stale pins to current size, but never raises a pin.

Backlog: cortex/backlog/408-enforce-the-verb-first-reference-size-direction-
with-a-down-only-ratchet.md
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from pathlib import Path


PIN_FILENAME = "size-pin.txt"

# A raise annotation mirrors the SKILL.md size-budget-exception marker:
# rationale >=30 chars, positive integer lifecycle-id, YYYY-MM-DD date.
RAISE_MARKER_REGEX = re.compile(
    r"^#\s*raised:\s*(?P<reason>.{30,}?),"
    r"\s*lifecycle-id=(?P<lid>\d+),"
    r"\s*date=(?P<date>\d{4}-\d{2}-\d{2})\s*$"
)

# Loose prefix detector — a line that looks like a raise annotation but does
# not fully match RAISE_MARKER_REGEX is an invalid marker, not a free comment.
RAISE_PREFIX_REGEX = re.compile(r"^#\s*raised:")

RAISE_MARKER_TEMPLATE = (
    "# raised: <reason >=30 chars>, lifecycle-id=<NNN>, date=<YYYY-MM-DD>"
)


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def enumerate_reference_dirs(root: Path) -> list[Path]:
    """Enumerate unique ``references/`` directories, canonical-first.

    Canonical ``skills/<name>/references/`` dirs come first, then plugin
    ``plugins/<plugin>/skills/<name>/references/`` dirs, then
    ``cortex_command/pipeline/prompts`` — review-shaping prose that is loaded
    like reference prose and so is pinned alongside it. Directories that are
    byte-identical to an earlier one (the rsync mirrors regenerated by
    ``just build-plugin``) are deduplicated by content hash, so an in-sync
    mirror collapses onto its canonical dir and a breach reports once.
    """
    candidates = (
        sorted((root / "skills").glob("*/references"))
        + sorted((root / "plugins").glob("*/skills/*/references"))
        + [root / "cortex_command" / "pipeline" / "prompts"]
    )
    seen_hashes: set[str] = set()
    unique: list[Path] = []
    for directory in candidates:
        if not directory.is_dir():
            continue
        digest = _dir_content_hash(directory)
        if digest in seen_hashes:
            continue
        seen_hashes.add(digest)
        unique.append(directory)
    return unique


def _dir_content_hash(directory: Path) -> str:
    """Hash of all regular files (relative path + bytes), pin file included."""
    hasher = hashlib.sha256()
    for path in sorted(_regular_files(directory)):
        hasher.update(str(path.relative_to(directory)).encode("utf-8"))
        hasher.update(b"\0")
        hasher.update(path.read_bytes())
        hasher.update(b"\0")
    return hasher.hexdigest()


def _regular_files(directory: Path) -> list[Path]:
    files: list[Path] = []
    for dirpath, _dirnames, filenames in os.walk(directory):
        for name in filenames:
            path = Path(dirpath) / name
            if path.is_file() and not path.is_symlink():
                files.append(path)
    return files


def measure(directory: Path) -> int:
    """Total bytes of all regular files under ``directory``, pin excluded."""
    return sum(
        path.stat().st_size
        for path in _regular_files(directory)
        if path.name != PIN_FILENAME
    )


def parse_pin(directory: Path) -> tuple[int | None, list[str]]:
    """Parse ``size-pin.txt``. Returns ``(pin_bytes, errors)``.

    A missing pin file is ``(None, [])`` — the caller renders the seeding
    message. A present-but-malformed file yields ``(None, errors)``.
    """
    pin_path = directory / PIN_FILENAME
    if not pin_path.is_file():
        return None, []

    errors: list[str] = []
    lines = pin_path.read_text(encoding="utf-8").splitlines()
    if not lines or not re.fullmatch(r"\d+", lines[0].strip()):
        first = lines[0].strip() if lines else ""
        errors.append(
            f"{pin_path}: first line must be an integer byte count, got {first!r}"
        )
        return None, errors

    pin = int(lines[0].strip())
    for lineno, line in enumerate(lines[1:], start=2):
        stripped = line.strip()
        if not stripped:
            continue
        if not stripped.startswith("#"):
            errors.append(
                f"{pin_path}: line {lineno} is neither blank nor a '#' comment: "
                f"{stripped!r}"
            )
        elif RAISE_PREFIX_REGEX.match(stripped) and not RAISE_MARKER_REGEX.match(
            stripped
        ):
            errors.append(
                f"{pin_path}: invalid raised-marker at line {lineno} — must match "
                f"'{RAISE_MARKER_TEMPLATE}'"
            )
    return pin, errors


def classify(directory: Path) -> list[str]:
    """Return all ratchet violations for ``directory`` (empty = clean)."""
    measured = measure(directory)
    pin, errors = parse_pin(directory)
    if pin is None and not errors:
        errors.append(
            f"{directory}: references directory has no {PIN_FILENAME} — the "
            f"first commit of a references directory sets its pin. Seed it at "
            f"the current size ({measured} bytes) via `just ratchet-refs`."
        )
    elif pin is not None and measured > pin:
        errors.append(
            f"{directory}: {measured} bytes exceeds its pin of {pin} "
            f"(+{measured - pin}). Reference prose follows verb-first "
            f"(cortex/requirements/project.md, Architectural Constraints): "
            f"move behavior into CLI verbs, keep only control flow — trim "
            f"within the directory rather than growing it. For growth a "
            f"correctness fix genuinely needs, raise the pin in "
            f"{PIN_FILENAME} with an annotated '{RAISE_MARKER_TEMPLATE}' "
            f"line and re-ratchet afterward. Lowering a pin is always "
            f"allowed: `just ratchet-refs`."
        )
    return errors


def ratchet_write(root: Path) -> int:
    """Seed missing pins and lower stale ones. Never raises. Returns exit code."""
    growth = 0
    for directory in enumerate_reference_dirs(root):
        measured = measure(directory)
        pin, errors = parse_pin(directory)
        pin_path = directory / PIN_FILENAME
        rel = directory.relative_to(root)
        if errors:
            for error in errors:
                print(error, file=sys.stderr)
            growth += 1
        elif pin is None:
            pin_path.write_text(f"{measured}\n", encoding="utf-8")
            print(f"seeded  {rel}: {measured}")
        elif measured < pin:
            pin_path.write_text(f"{measured}\n", encoding="utf-8")
            print(f"lowered {rel}: {pin} -> {measured}")
        elif measured > pin:
            print(
                f"GROWTH  {rel}: {measured} > pin {pin} — not raised. Trim, or "
                f"hand-raise with '{RAISE_MARKER_TEMPLATE}'.",
                file=sys.stderr,
            )
            growth += 1
        else:
            print(f"pinned  {rel}: {pin}")
    return 1 if growth else 0


def check(root: Path) -> int:
    """Report all violations across the repo. Returns exit code."""
    all_errors: list[str] = []
    for directory in enumerate_reference_dirs(root):
        all_errors.extend(classify(directory))
    for error in all_errors:
        print(error, file=sys.stderr)
    if not all_errors:
        print("reference-size ratchet: all directories within their pins")
    return 1 if all_errors else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--write",
        action="store_true",
        help="seed missing pins and lower stale ones (down-only; never raises)",
    )
    args = parser.parse_args(argv)
    root = repo_root()
    return ratchet_write(root) if args.write else check(root)


if __name__ == "__main__":
    raise SystemExit(main())
