#!/usr/bin/env python3
"""One-shot helper to sweep `/cortex:<skill>` -> `/cortex-<plugin>:<skill>` across
the in-scope source tree for ticket 122 (R8).

Rewrites every `/cortex:<skill>` reference in the listed files to use the
post-install plugin namespace based on the canonical mapping derived from
`justfile:423-432`:

  cortex-interactive            -> 14 skills
  cortex-overnight-integration  -> overnight, morning-review

Carve-outs (lines that should NOT be rewritten — they document literal
historical input strings, not invocations):

  skills/retro/SKILL.md:38 — "/cortex:retro ---" (validation example)
  skills/retro/SKILL.md:43 — "/cortex:retro !!!" (sanitization example)

Edits are applied to the top-level source tree only. Plugin trees
(`plugins/cortex-interactive/skills/`, `plugins/cortex-overnight-integration/skills/`)
are regenerated by `just build-plugin` in a follow-up task and MUST NOT be
edited here.

Stdlib-only. Idempotent: a second run is a no-op.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Canonical mapping (derived from justfile:423-432)
# ---------------------------------------------------------------------------

CORTEX_INTERACTIVE_SKILLS = {
    "commit",
    "pr",
    "lifecycle",
    "backlog",
    "requirements",
    "research",
    "discovery",
    "refine",
    "retro",
    "dev",
    "fresh",
    "diagnose",
    "evolve",
    "critical-review",
}

CORTEX_OVERNIGHT_INTEGRATION_SKILLS = {
    "overnight",
    "morning-review",
}

SKILL_OWNER: dict[str, str] = {}
for s in CORTEX_INTERACTIVE_SKILLS:
    SKILL_OWNER[s] = "cortex-interactive"
for s in CORTEX_OVERNIGHT_INTEGRATION_SKILLS:
    SKILL_OWNER[s] = "cortex-overnight-integration"


# ---------------------------------------------------------------------------
# Files in scope (Task 8 explicit list)
# ---------------------------------------------------------------------------

IN_SCOPE_FILES: tuple[str, ...] = (
    "CLAUDE.md",
    "README.md",
    "docs/agentic-layer.md",
    "docs/backlog.md",
    "docs/dashboard.md",
    "docs/interactive-phases.md",
    "docs/overnight-operations.md",
    "docs/overnight.md",
    "docs/plugin-development.md",
    "docs/skills-reference.md",
    "skills/backlog/SKILL.md",
    "skills/backlog/references/schema.md",
    "skills/commit/SKILL.md",
    "skills/critical-review/SKILL.md",
    "skills/dev/SKILL.md",
    "skills/diagnose/SKILL.md",
    "skills/discovery/SKILL.md",
    "skills/discovery/references/auto-scan.md",
    "skills/discovery/references/clarify.md",
    "skills/discovery/references/decompose.md",
    "skills/discovery/references/research.md",
    "skills/evolve/SKILL.md",
    "skills/fresh/SKILL.md",
    "skills/lifecycle/SKILL.md",
    "skills/lifecycle/references/clarify-critic.md",
    "skills/lifecycle/references/complete.md",
    "skills/lifecycle/references/implement.md",
    "skills/lifecycle/references/plan.md",
    "skills/lifecycle/references/research.md",
    "skills/lifecycle/references/specify.md",
    "skills/pr/SKILL.md",
    "skills/refine/SKILL.md",
    "skills/refine/references/clarify-critic.md",
    "skills/refine/references/specify.md",
    "skills/requirements/SKILL.md",
    "skills/requirements/references/gather.md",
    "skills/research/SKILL.md",
    "skills/retro/SKILL.md",
    "tests/baseline_critical_review.py",
    "tests/test_critical_review_classifier.py",
    "tests/test_skill_callgraph.py",
    "tests/test_hooks.sh",
    "tests/test_skill_behavior.sh",
    "scripts/validate-callgraph.py",
    "tests/scenarios/commit/time-pressure.yaml",
    "hooks/cortex-scan-lifecycle.sh",
    "cortex_command/init/templates/retros/README.md",
)


# ---------------------------------------------------------------------------
# Carve-outs: (relative-path, 1-based line number, exact substring to skip)
#
# Each entry suppresses rewriting on the named line if the line contains the
# given substring. Use the smallest substring that uniquely matches the
# historical-input occurrence so we do NOT skip other rewrites on the same
# line.
# ---------------------------------------------------------------------------

CARVE_OUTS: tuple[tuple[str, int, str], ...] = (
    # Validation example for empty-after-sanitization input.
    ("skills/retro/SKILL.md", 38, '"/cortex:retro ---"'),
    # Sanitization example for invalid-character input.
    ("skills/retro/SKILL.md", 43, "`/cortex:retro !!!`"),
)


# ---------------------------------------------------------------------------
# Rewrite logic
# ---------------------------------------------------------------------------

# Match `/cortex:<skill>` where <skill> starts with a lowercase letter and is
# composed of [a-z0-9-]. Uses a leading negative-lookbehind to avoid matching
# inside identifiers (e.g. `xx/cortex:foo` is unlikely but the verifier uses
# the same guard, so stay consistent).
OLD_FORM_RE = re.compile(
    r"(?<![A-Za-z0-9_-])/cortex:([a-z][a-z0-9-]*)"
)


def line_has_carveout(rel_path: str, lineno: int) -> tuple[bool, str | None]:
    """Return (True, needle) if the line is carved out, else (False, None)."""
    for cf, cl, needle in CARVE_OUTS:
        if cf == rel_path and cl == lineno:
            return True, needle
    return False, None


def rewrite_line(rel_path: str, lineno: int, line: str) -> tuple[str, int]:
    """Return (new_line, replacements_made).

    If the line is carved out, the carve-out substring is preserved verbatim
    while other matches on the same line are still rewritten.
    """
    carved, needle = line_has_carveout(rel_path, lineno)
    if not carved:
        new, n = OLD_FORM_RE.subn(_sub, line)
        return new, n
    # Split the line on the carve-out needle and rewrite each non-carved
    # segment independently. If the needle isn't found (line numbers shifted),
    # fall through to a normal rewrite — verifier will catch the survivor.
    if needle is None or needle not in line:
        new, n = OLD_FORM_RE.subn(_sub, line)
        return new, n
    parts = line.split(needle)
    rewritten_parts: list[str] = []
    total = 0
    for i, part in enumerate(parts):
        new_part, n = OLD_FORM_RE.subn(_sub, part)
        rewritten_parts.append(new_part)
        total += n
    return needle.join(rewritten_parts), total


def _sub(match: re.Match[str]) -> str:
    skill = match.group(1)
    owner = SKILL_OWNER.get(skill)
    if owner is None:
        # Unknown skill — leave the original text intact. The verifier will
        # surface this as `unknown-skill` if it slipped through.
        return match.group(0)
    return f"/{owner}:{skill}"


def sweep_file(root: Path, rel_path: str) -> tuple[int, int]:
    """Rewrite a single file. Returns (lines_changed, replacements)."""
    abs_path = root / rel_path
    if not abs_path.exists():
        sys.stderr.write(f"[skip] missing: {rel_path}\n")
        return 0, 0
    text = abs_path.read_text(encoding="utf-8")
    out_lines: list[str] = []
    changed_lines = 0
    total_replacements = 0
    # Preserve trailing newline behavior by splitting with keepends.
    for lineno, line in enumerate(text.splitlines(keepends=True), start=1):
        # Strip the trailing newline for matching, then re-attach.
        if line.endswith("\r\n"):
            body, eol = line[:-2], "\r\n"
        elif line.endswith("\n"):
            body, eol = line[:-1], "\n"
        else:
            body, eol = line, ""
        new_body, n = rewrite_line(rel_path, lineno, body)
        if n > 0:
            changed_lines += 1
            total_replacements += n
        out_lines.append(new_body + eol)
    new_text = "".join(out_lines)
    if new_text != text:
        try:
            abs_path.write_text(new_text, encoding="utf-8")
        except PermissionError as exc:
            sys.stderr.write(
                f"[error] cannot write {rel_path}: {exc}. "
                "Edit manually and re-run with --verify-only.\n"
            )
            return changed_lines, total_replacements
    return changed_lines, total_replacements


def main(argv: list[str] | None = None) -> int:
    root = Path(__file__).resolve().parent.parent
    grand_lines = 0
    grand_repls = 0
    files_touched = 0
    for rel in IN_SCOPE_FILES:
        lines, repls = sweep_file(root, rel)
        if repls:
            files_touched += 1
            print(f"  {rel}: {lines} line(s), {repls} replacement(s)")
        grand_lines += lines
        grand_repls += repls
    print(
        f"sweep complete: {files_touched} files touched, "
        f"{grand_lines} lines changed, {grand_repls} replacements made"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
